services:
  #For now kafka and zookeeper aren't needed at all, so they are disabled

  # # Zookeeper (Required for Kafka)
  # zookeeper:
  #   image: bitnami/zookeeper:latest
  #   environment:
  #     - ALLOW_ANONYMOUS_LOGIN=yes
  #   ports:
  #     - "2181:2181"

  # # Kafka (Streaming Platform)
  # kafka:
  #   image: bitnami/kafka:latest
  #   depends_on:
  #     - zookeeper
  #   environment:
  #     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #   ports:
  #     - "9092:9092"

  # PostgreSQL (Metadata Store + Airflow)
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=metadata_db
    ports:
      - "5432:5432"

  # Apache Spark (Master node)
  # HDFS + Delta lake are contained inside this image
  spark:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"

  # Missing Apache Spark (workers)

  # Apache Airflow (Workflow Orchestration)
  # Fixed version 2.10.0 to avoid nightmares with SQLAlchemy and other packages
  airflow:
    image: apache/airflow:2.10.0
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:admin@postgres:5432/metadata_db
    ports:
      - "8080:8080"

networks:
  bigdata_network:
    driver: bridge

# TODO: Define which volumes are really needed 
# Probably will only be persistent storages of db's / filesystems
# and airflow logs 
volumes:
  postgres_storage:
  #kafka_data:
  spark_data:
  airflow_logs:
