include:
  - airflow-compose.yaml
  #- kafka-compose.yaml
  #- spark-compose.yaml

services:
  streamlit-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit-frontend
    networks: 
      - bigdata_network
    ports:
      - 9999:9999
    working_dir: /app 
    restart: unless-stopped

networks:
  bigdata_network:
    driver: bridge

