FROM --platform=linux/amd64 bitnami/spark:3.5.1

USER root
RUN pip install --no-cache-dir delta-spark==3.2.0

USER 1001

RUN export PYSPARK_SUBMIT_ARGS="--packages io.delta:delta-core_2.12:3.2.0 pyspark-shell"