
services:
  # Zookeeper (Required for Kafka)
  # Fixed 3.9.3 version
  kafka-zookeeper:
    image: bitnami/zookeeper:3.9.3
    container_name: kafka-zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    restart: unless-stopped

  # Kafka (Streaming Platform)
  # Fixed 3.9.0 version
  kafka:
    image: bitnami/kafka:3.9.0
    container_name: kafka
    depends_on:
      - kafka-zookeeper
    restart: unless-stopped
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: kafka-zookeeper:2181
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29092,INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONFLUENT_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 1
      KAFKA_MESSAGE_MAX_BYTES: 1000000        # Max 100 MB
      log.retention.ms: 3600000             # Retain messages for only 1h 

  stream-manager:
    build:
      context: .
      dockerfile: Dockerfile.stream
    container_name: stream-manager
    depends_on:
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - BLUESKY_EMAIL=${BLUESKY_EMAIL}
      - BLUESKY_PASSWORD=${BLUESKY_PASSWORD}
      - TWITTER_API_KEY=${TWITTER_API_KEY}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    restart: unless-stopped

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8082:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "kafka"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"
      KAFKA_CLUSTERS_0_ZOOKEEPER: "kafka-zookeeper:2181"
    restart: unless-stopped

