producers:
  - name: "bluesky-batch-producer"
    py_object: "src.ingestion.batch.bluesky_batch:BlueskyBatchProducer"
    kwargs:
      posts_batch_size: 100
      likes_batch_size: 100
    db:
      type: "jsonl-file"
      kwargs:
        folder: "data_lake/landing/temporal"