kafka:
  bootstrap_servers: "localhost:9092" # This should probably be extracted from the docker compose somehow
  local_test: False
  topics:
    - name: "youtube_metadata"
      num_partitions: 1
      replication_factor: 1
    - name: "youtube_caption"
      num_partitions: 1
      replication_factor: 1
    - name: "youtube_comment"
      num_partitions: 1
      replication_factor: 1
    - name: "twitter_topic"
      num_partitions: 1
      replication_factor: 1
    - name: "bluesky_topic"
      num_partitions: 1
      replication_factor: 1
    - name: "test_topic"
      num_partitions: 1
      replication_factor: 1

# Custom orchestration for streaming (Opposed to airflow batch)
# Time units are represented by seconds
orchestration:
  producer_interleaving_time: 5
  max_streaming_duration: 300   #5 mins